# Railway Configuration File
# Optimized for PNPtv Telegram Bot deployment

[build]
builder = "nixpacks"
buildCommand = "npm install --production=false"

[deploy]
startCommand = "node start-production.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 30

# Resource optimization
[deploy.resources]
# Remove memory limits to let Railway auto-scale
# memory = 512  # Optional: Uncomment to set explicit limit (MB)

# Environment detection
[env]
NODE_ENV = "production"

# Deployment settings
[deploy.regions]
# Automatically deploy to optimal region
# Options: us-west1, us-east4, europe-west4, asia-southeast1

# Observability
[observability]
# Enable better logging
logsRetention = 7  # days

# Network configuration
[network]
# Railway will auto-assign PORT
