#!/bin/bash

# PNPtv Payment System - Vercel Deployment Script
# This script automates the deployment process

set -e

echo "=========================================="
echo "PNPtv Payment System - Vercel Deployment"
echo "=========================================="
echo ""

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Installing..."
    npm i -g vercel
fi

echo "✓ Vercel CLI ready"
echo ""

# Navigate to project
cd /root/Bots/pnptv-payment

echo "📦 Building project..."
npm run build
echo "✓ Build successful"
echo ""

echo "⚠️  You will now need to:"
echo ""
echo "1️⃣  DEPLOYMENT OPTIONS:"
echo "   Option A: Using Vercel GitHub Integration (Recommended)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   • Push code to GitHub: git push origin main"
echo "   • Go to https://vercel.com/dashboard"
echo "   • Click 'Add New' → 'Project'"
echo "   • Import your pnptv-payment repository"
echo "   • Skip environment variables (do next)"
echo ""
echo "   Option B: Using Vercel CLI (Quick)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   • Run: vercel"
echo "   • Follow prompts to link your account"
echo "   • Skip setting env vars"
echo ""
echo "2️⃣  ENVIRONMENT VARIABLES:"
echo "   After deployment, add these to Vercel project:"
echo ""
echo "   REQUIRED (Production Use):"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   • NEXT_PUBLIC_RECIPIENT_ADDRESS = your_daimo_wallet"
echo "   • FIREBASE_PROJECT_ID = your_firebase_id"
echo "   • FIREBASE_CLIENT_EMAIL = your_firebase_email"
echo "   • FIREBASE_PRIVATE_KEY = your_firebase_key"
echo "   • FIREBASE_DATABASE_URL = your_firebase_url"
echo "   • WEBHOOK_SECRET = $(openssl rand -hex 32)"
echo "   • NODE_ENV = production"
echo ""
echo "   OPTIONAL (Monitoring):"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   • NEXT_PUBLIC_SENTRY_DSN = your_sentry_dsn"
echo "   • SENTRY_AUTH_TOKEN = your_sentry_token"
echo ""
echo "3️⃣  HOW TO ADD ENV VARS TO VERCEL:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Method A: Dashboard"
echo "   1. Go to https://vercel.com/dashboard"
echo "   2. Select your pnptv-payment project"
echo "   3. Settings → Environment Variables"
echo "   4. Add each variable (set to Production)"
echo "   5. Redeploy: Deployments → Redeploy"
echo ""
echo "   Method B: CLI"
echo "   1. vercel env add NEXT_PUBLIC_RECIPIENT_ADDRESS"
echo "   2. vercel env add FIREBASE_PROJECT_ID"
echo "   3. (repeat for all vars)"
echo "   4. vercel --prod"
echo ""
echo "4️⃣  SENTRY SETUP (Optional but Recommended):"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   1. Create account: https://sentry.io"
echo "   2. Create project → Next.js"
echo "   3. Get DSN from project settings"
echo "   4. Add NEXT_PUBLIC_SENTRY_DSN to Vercel"
echo ""
echo "5️⃣  VERIFY DEPLOYMENT:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   ✓ App loads at: https://your-project.vercel.app"
echo "   ✓ UI displays correctly"
echo "   ✓ No console errors"
echo "   ✓ Webhook endpoint accessible"
echo "   ✓ Firebase connected (logs processed)"
echo ""
echo "=========================================="
echo "📚 For detailed instructions, see:"
echo "   • DEPLOYMENT_GUIDE.md"
echo "   • MONITORING_SETUP.md"
echo "   • README.md"
echo "=========================================="
echo ""
echo "Ready to deploy? Run:"
echo "   vercel"